/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExtendedEmbedsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian12 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/utils/settings-compat.ts
var import_obsidian = require("obsidian");
var ObsidianModule = __toESM(require("obsidian"), 1);
function createSettingsGroup(containerEl, heading, desc) {
  if ((0, import_obsidian.requireApiVersion)("1.11.0")) {
    const SettingGroupClass = ObsidianModule.SettingGroup;
    if (SettingGroupClass) {
      const group = new SettingGroupClass(containerEl);
      if (heading) group.setHeading(heading);
      if (desc) {
        if (typeof group.setDesc === "function") {
          group.setDesc(desc);
        } else {
          containerEl.createEl("p", { text: desc, cls: "setting-item-description" });
        }
      }
      return {
        addSetting(cb) {
          group.addSetting(cb);
        }
      };
    }
  }
  if (heading) {
    const headingEl = containerEl.createDiv("setting-group-heading");
    headingEl.createEl("h3", { text: heading });
  }
  if (desc) {
    containerEl.createEl("p", { text: desc, cls: "setting-item-description" });
  }
  return {
    addSetting(cb) {
      const setting = new import_obsidian.Setting(containerEl);
      cb(setting);
    }
  };
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  enableVimeo: true,
  enableSpotify: true,
  enableAppleMusic: true,
  enableSoundcloud: true,
  enableBandcamp: true,
  enableCodepen: true,
  enableFigma: true,
  enableGithubGist: true,
  enableGithubRepo: true,
  enableGithubIssue: true,
  enableReddit: true,
  enableBluesky: true,
  enableMastodon: true,
  enableLinkedin: true,
  enableSteam: true,
  enableOpengraph: true,
  githubToken: "",
  githubTokenSecretId: "",
  themeMode: "auto",
  cacheTtlMinutes: 60
};
var ExtendedEmbedsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const providersGroup = createSettingsGroup(containerEl, "Providers");
    this.addProviderToggle(providersGroup, "Vimeo", "enableVimeo");
    this.addProviderToggle(providersGroup, "Spotify", "enableSpotify");
    this.addProviderToggle(providersGroup, "Apple Music", "enableAppleMusic");
    this.addProviderToggle(providersGroup, "SoundCloud", "enableSoundcloud");
    this.addProviderToggle(providersGroup, "Bandcamp", "enableBandcamp");
    this.addProviderToggle(providersGroup, "CodePen", "enableCodepen");
    this.addProviderToggle(providersGroup, "Figma", "enableFigma");
    this.addProviderToggle(providersGroup, "GitHub Gist", "enableGithubGist");
    this.addProviderToggle(providersGroup, "GitHub repository", "enableGithubRepo");
    this.addProviderToggle(providersGroup, "GitHub issue/PR", "enableGithubIssue");
    this.addProviderToggle(providersGroup, "Reddit", "enableReddit");
    this.addProviderToggle(providersGroup, "Bluesky", "enableBluesky");
    this.addProviderToggle(providersGroup, "Mastodon", "enableMastodon");
    this.addProviderToggle(providersGroup, "LinkedIn", "enableLinkedin");
    this.addProviderToggle(providersGroup, "Steam", "enableSteam");
    this.addProviderToggle(providersGroup, "Generic URL preview (Open Graph)", "enableOpengraph");
    const githubGroup = createSettingsGroup(containerEl, "GitHub");
    githubGroup.addSetting((setting) => {
      setting.setName("Personal access token");
      if ((0, import_obsidian2.requireApiVersion)("1.11.4")) {
        setting.setDesc("Choose a secret that contains your GitHub personal access token. Only needs public repo read access.").addComponent((el) => {
          const obsidian = require("obsidian");
          const SecretComponent = obsidian.SecretComponent;
          const component = new SecretComponent(this.app, el);
          component.setValue(this.plugin.settings.githubTokenSecretId);
          component.onChange((value) => {
            void (async () => {
              this.plugin.settings.githubTokenSecretId = value;
              await this.plugin.saveSettings();
            })();
          });
          return component;
        });
      } else {
        setting.setDesc("Optional. Increases API rate limit from 60 to 5,000 requests/hour. Only needs public repo read access.").addText(
          (text) => text.setPlaceholder("Paste token here").setValue(this.plugin.settings.githubToken).onChange(async (value) => {
            this.plugin.settings.githubToken = value;
            await this.plugin.saveSettings();
          })
        );
      }
    });
    const displayGroup = createSettingsGroup(containerEl, "Display");
    displayGroup.addSetting((setting) => {
      setting.setName("Theme mode").setDesc("How embeds determine dark/light styling. Auto follows your Obsidian theme.").addDropdown(
        (dropdown) => dropdown.addOption("auto", "Auto (follow Obsidian)").addOption("dark", "Always dark").addOption("light", "Always light").setValue(this.plugin.settings.themeMode).onChange(async (value) => {
          this.plugin.settings.themeMode = value;
          await this.plugin.saveSettings();
        })
      );
    });
    const cacheGroup = createSettingsGroup(containerEl, "Cache");
    cacheGroup.addSetting((setting) => {
      setting.setName("Cache duration (minutes)").setDesc("How long fetched data is cached in memory. Set to 0 to disable caching.").addSlider(
        (slider) => slider.setLimits(0, 1440, 15).setValue(this.plugin.settings.cacheTtlMinutes).setDynamicTooltip().onChange(async (value) => {
          this.plugin.settings.cacheTtlMinutes = value;
          await this.plugin.saveSettings();
        })
      );
    });
  }
  addProviderToggle(group, name, key) {
    group.addSetting((setting) => {
      setting.setName(name).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings[key]).onChange(async (value) => {
          this.plugin.settings[key] = value;
          await this.plugin.saveSettings();
        })
      );
    });
  }
};

// src/cache.ts
function createCacheManager(ttlMinutes) {
  const store = /* @__PURE__ */ new Map();
  return {
    get(key) {
      const entry = store.get(key);
      if (!entry) return null;
      if (Date.now() > entry.expires) {
        store.delete(key);
        return null;
      }
      return entry.data;
    },
    set(key, data) {
      store.set(key, {
        data,
        expires: Date.now() + ttlMinutes * 60 * 1e3
      });
    },
    clear() {
      store.clear();
    }
  };
}

// src/embed-manager.ts
var import_obsidian11 = require("obsidian");

// src/providers/vimeo.ts
var VIMEO_PATTERNS = [
  /^https?:\/\/(?:www\.)?vimeo\.com\/(\d+)/,
  /^https?:\/\/(?:www\.)?vimeo\.com\/manage\/videos\/(\d+)/,
  /^https?:\/\/player\.vimeo\.com\/video\/(\d+)/
];
function extractVimeoId(url) {
  for (const pattern of VIMEO_PATTERNS) {
    const match = url.match(pattern);
    if (match && match[1]) return match[1];
  }
  return null;
}
var vimeoProvider = {
  id: "vimeo",
  name: "Vimeo",
  test(url) {
    return extractVimeoId(url) !== null;
  },
  render(url, container, _theme) {
    const videoId = extractVimeoId(url);
    if (!videoId) return;
    const embedUrl = `https://player.vimeo.com/video/${videoId}?badge=0&autopause=0&player_id=0&app_id=58479`;
    container.addClass("extended-embed", "extended-embed-vimeo");
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        frameborder: "0",
        allow: "autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share",
        allowfullscreen: "",
        referrerpolicy: "strict-origin-when-cross-origin",
        loading: "lazy"
      }
    });
  }
};

// src/providers/spotify.ts
var SPOTIFY_PATTERN = /open\.spotify\.com\/(track|album|playlist|episode|show)\/([a-zA-Z0-9]+)/;
var SPOTIFY_PODCAST_PATTERN = /(podcasters|creators)\.spotify\.com\/pod\/(show|profile)\/([^/]+)\/(embed\/)?episodes\/([^/]+)\/([^/?#]+)/;
function isPodcastUrl(url) {
  return SPOTIFY_PODCAST_PATTERN.test(url);
}
function getPodcastEmbedUrl(url) {
  if (url.includes("/embed/")) {
    return url.replace(/^https?:\/\/(creators|podcasters)\.spotify\.com/, "https://podcasters.spotify.com");
  }
  const match = url.match(SPOTIFY_PODCAST_PATTERN);
  if (!match) return url;
  const [, , , user, , slug, id] = match;
  return `https://podcasters.spotify.com/pod/show/${user}/embed/episodes/${slug}/${id}`;
}
var spotifyProvider = {
  id: "spotify",
  name: "Spotify",
  test(url) {
    return SPOTIFY_PATTERN.test(url) || isPodcastUrl(url);
  },
  render(url, container, theme) {
    container.addClass("extended-embed", "extended-embed-spotify");
    if (isPodcastUrl(url)) {
      const embedUrl2 = getPodcastEmbedUrl(url);
      container.createEl("iframe", {
        attr: {
          src: embedUrl2,
          frameborder: "0",
          allow: "autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture",
          loading: "lazy",
          scrolling: "no",
          style: "height: 102px; overflow: hidden"
        }
      });
      return;
    }
    const match = url.match(SPOTIFY_PATTERN);
    if (!match) return;
    const [, type, id] = match;
    const themeParam = theme === "dark" ? "&theme=0" : "";
    const embedUrl = `https://open.spotify.com/embed/${type}/${id}?utm_source=generator${themeParam}`;
    const isCompact = type === "track";
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        frameborder: "0",
        allow: "autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture",
        loading: "lazy",
        style: `height: ${isCompact ? "152px" : "352px"}`
      }
    });
  }
};

// src/providers/apple-music.ts
var APPLE_MUSIC_PATTERN = /music\.apple\.com\/([a-z]{2})\/(album|playlist|song|music-video|station)\/([^?#]+)/;
var appleMusicProvider = {
  id: "apple-music",
  name: "Apple Music",
  test(url) {
    return APPLE_MUSIC_PATTERN.test(url);
  },
  render(url, container, theme) {
    const match = url.match(APPLE_MUSIC_PATTERN);
    if (!match) return;
    const embedUrl = url.replace("music.apple.com", "embed.music.apple.com");
    const themeParam = theme === "dark" ? "" : "&l=en-US";
    const type = match[2];
    const isSingle = type === "song" || url.includes("?i=");
    container.addClass("extended-embed", "extended-embed-apple-music");
    container.createEl("iframe", {
      attr: {
        src: `${embedUrl}${themeParam}`,
        frameborder: "0",
        allow: "autoplay *; encrypted-media *; fullscreen *; clipboard-write",
        sandbox: "allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation",
        loading: "lazy",
        style: `height: ${isSingle ? "175px" : "450px"}`
      }
    });
  }
};

// src/providers/soundcloud.ts
var SOUNDCLOUD_PATTERN = /soundcloud\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+/;
var soundcloudProvider = {
  id: "soundcloud",
  name: "SoundCloud",
  test(url) {
    return SOUNDCLOUD_PATTERN.test(url);
  },
  render(url, container, theme) {
    const colorParam = theme === "dark" ? "&color=%23ff5500" : "&color=%23ff5500";
    const visualParam = "&visual=true&show_artwork=true&show_comments=false&show_user=true&show_reposts=false";
    const embedUrl = `https://w.soundcloud.com/player/?url=${encodeURIComponent(url)}${colorParam}${visualParam}&auto_play=false`;
    container.addClass("extended-embed", "extended-embed-soundcloud");
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        frameborder: "0",
        allow: "autoplay",
        loading: "lazy",
        scrolling: "no"
      }
    });
  }
};

// src/providers/bandcamp.ts
var import_obsidian3 = require("obsidian");
var BANDCAMP_PATTERN = /([a-zA-Z0-9_-]+)\.bandcamp\.com\/(track|album)\/([a-zA-Z0-9_-]+)/;
var bandcampProvider = {
  id: "bandcamp",
  name: "Bandcamp",
  test(url) {
    return BANDCAMP_PATTERN.test(url);
  },
  async render(url, container, theme) {
    var _a;
    const match = url.match(BANDCAMP_PATTERN);
    if (!match) return;
    const isAlbum = match[2] === "album";
    container.addClass("extended-embed", "extended-embed-bandcamp");
    const loading = container.createDiv("extended-embed-loading");
    loading.setText("Loading embed...");
    let itemId = null;
    try {
      const response = await (0, import_obsidian3.requestUrl)({ url, headers: { Accept: "text/html" } });
      const html = response.text;
      const idMatch = html.match(/"item_id","value":(\d+)/);
      if (idMatch) {
        itemId = (_a = idMatch[1]) != null ? _a : null;
      }
    } catch (e) {
      loading.setText("Failed to load embed");
      loading.addClass("extended-embed-error");
      return;
    }
    if (!itemId) {
      loading.setText("Failed to load embed");
      loading.addClass("extended-embed-error");
      return;
    }
    loading.remove();
    const bgColor = theme === "dark" ? "333333" : "ffffff";
    const accent = getComputedStyle(document.body).getPropertyValue("--interactive-accent").trim();
    const linkColor = accent.startsWith("#") ? accent.slice(1) : "0687f5";
    const typeParam = isAlbum ? "album" : "track";
    const embedUrl = `https://bandcamp.com/EmbeddedPlayer/${typeParam}=${itemId}/size=large/bgcol=${bgColor}/linkcol=${linkColor}/tracklist=false/artwork=small/transparent=true/`;
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        frameborder: "0",
        seamless: "",
        loading: "lazy",
        style: "height: 120px"
      }
    });
  }
};

// src/providers/codepen.ts
var CODEPEN_PATTERN = /codepen\.io\/([a-zA-Z0-9_-]+)\/(?:pen|full|details)\/([a-zA-Z0-9]+)/;
var codepenProvider = {
  id: "codepen",
  name: "CodePen",
  test(url) {
    return CODEPEN_PATTERN.test(url);
  },
  render(url, container, theme) {
    const match = url.match(CODEPEN_PATTERN);
    if (!match) return;
    const [, user, penId] = match;
    const themeParam = theme === "dark" ? "dark" : "light";
    const embedUrl = `https://codepen.io/${user}/embed/${penId}?default-tab=result&editable=true&theme-id=${themeParam}`;
    container.addClass("extended-embed", "extended-embed-codepen");
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        frameborder: "0",
        allowfullscreen: "",
        allow: "autoplay; clipboard-write; encrypted-media",
        loading: "lazy",
        scrolling: "no"
      }
    });
  }
};

// src/providers/figma.ts
var FIGMA_PATTERN = /figma\.com\/(file|proto|design|board|slides|deck)\/([a-zA-Z0-9]+)/;
var figmaProvider = {
  id: "figma",
  name: "Figma",
  test(url) {
    return FIGMA_PATTERN.test(url);
  },
  render(url, container, _theme) {
    const match = url.match(FIGMA_PATTERN);
    if (!match) return;
    const embedUrl = `https://www.figma.com/embed?embed_host=obsidian&url=${encodeURIComponent(url)}`;
    container.addClass("extended-embed", "extended-embed-figma");
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        frameborder: "0",
        allowfullscreen: "",
        loading: "lazy"
      }
    });
  }
};

// src/providers/github-gist.ts
var import_obsidian4 = require("obsidian");

// src/providers/brand-icons.ts
var SVG_NS = "http://www.w3.org/2000/svg";
function createSvg(viewBox, paths) {
  const svg = document.createElementNS(SVG_NS, "svg");
  svg.setAttribute("viewBox", viewBox);
  svg.setAttribute("width", "24");
  svg.setAttribute("height", "24");
  svg.setAttribute("fill", "currentColor");
  svg.classList.add("extended-embed-brand-icon");
  for (const d of paths) {
    const path = document.createElementNS(SVG_NS, "path");
    path.setAttribute("d", d);
    svg.appendChild(path);
  }
  return svg;
}
function blueskyIcon() {
  return createSvg("0 0 640 640", [
    "M439.8 358.7C436.5 358.3 433.1 357.9 429.8 357.4C433.2 357.8 436.5 358.3 439.8 358.7zM320 291.1C293.9 240.4 222.9 145.9 156.9 99.3C93.6 54.6 69.5 62.3 53.6 69.5C35.3 77.8 32 105.9 32 122.4C32 138.9 41.1 258 47 277.9C66.5 343.6 136.1 365.8 200.2 358.6C203.5 358.1 206.8 357.7 210.2 357.2C206.9 357.7 203.6 358.2 200.2 358.6C106.3 372.6 22.9 406.8 132.3 528.5C252.6 653.1 297.1 501.8 320 425.1C342.9 501.8 369.2 647.6 505.6 528.5C608 425.1 533.7 372.5 439.8 358.6C436.5 358.2 433.1 357.8 429.8 357.3C433.2 357.7 436.5 358.2 439.8 358.6C503.9 365.7 573.4 343.5 593 277.9C598.9 258 608 139 608 122.4C608 105.8 604.7 77.7 586.4 69.5C570.6 62.4 546.4 54.6 483.2 99.3C417.1 145.9 346.1 240.4 320 291.1z"
  ]);
}
function githubIcon() {
  return createSvg("0 0 640 640", [
    "M237.9 461.4C237.9 463.4 235.6 465 232.7 465C229.4 465.3 227.1 463.7 227.1 461.4C227.1 459.4 229.4 457.8 232.3 457.8C235.3 457.5 237.9 459.1 237.9 461.4zM206.8 456.9C206.1 458.9 208.1 461.2 211.1 461.8C213.7 462.8 216.7 461.8 217.3 459.8C217.9 457.8 216 455.5 213 454.6C210.4 453.9 207.5 454.9 206.8 456.9zM251 455.2C248.1 455.9 246.1 457.8 246.4 460.1C246.7 462.1 249.3 463.4 252.3 462.7C255.2 462 257.2 460.1 256.9 458.1C256.6 456.2 253.9 454.9 251 455.2zM316.8 72C178.1 72 72 177.3 72 316C72 426.9 141.8 521.8 241.5 555.2C254.3 557.5 258.8 549.6 258.8 543.1C258.8 536.9 258.5 502.7 258.5 481.7C258.5 481.7 188.5 496.7 173.8 451.9C173.8 451.9 162.4 422.8 146 415.3C146 415.3 123.1 399.6 147.6 399.9C147.6 399.9 172.5 401.9 186.2 425.7C208.1 464.3 244.8 453.2 259.1 446.6C261.4 430.6 267.9 419.5 275.1 412.9C219.2 406.7 162.8 398.6 162.8 302.4C162.8 274.9 170.4 261.1 186.4 243.5C183.8 237 175.3 210.2 189 175.6C209.9 169.1 258 202.6 258 202.6C278 197 299.5 194.1 320.8 194.1C342.1 194.1 363.6 197 383.6 202.6C383.6 202.6 431.7 169 452.6 175.6C466.3 210.3 457.8 237 455.2 243.5C471.2 261.2 481 275 481 302.4C481 398.9 422.1 406.6 366.2 412.9C375.4 420.8 383.2 435.8 383.2 459.3C383.2 493 382.9 534.7 382.9 542.9C382.9 549.4 387.5 557.3 400.2 555C500.2 521.8 568 426.9 568 316C568 177.3 455.5 72 316.8 72zM169.2 416.9C167.9 417.9 168.2 420.2 169.9 422.1C171.5 423.7 173.8 424.4 175.1 423.1C176.4 422.1 176.1 419.8 174.4 417.9C172.8 416.3 170.5 415.6 169.2 416.9zM158.4 408.8C157.7 410.1 158.7 411.7 160.7 412.7C162.3 413.7 164.3 413.4 165 412C165.7 410.7 164.7 409.1 162.7 408.1C160.7 407.5 159.1 407.8 158.4 408.8zM190.8 444.4C189.2 445.7 189.8 448.7 192.1 450.6C194.4 452.9 197.3 453.2 198.6 451.6C199.9 450.3 199.3 447.3 197.3 445.4C195.1 443.1 192.1 442.8 190.8 444.4zM179.4 429.7C177.8 430.7 177.8 433.3 179.4 435.6C181 437.9 183.7 438.9 185 437.9C186.6 436.6 186.6 434 185 431.7C183.6 429.4 181 428.4 179.4 429.7z"
  ]);
}
function redditIcon() {
  return createSvg("0 0 640 640", [
    "M64 320C64 178.6 178.6 64 320 64C461.4 64 576 178.6 576 320C576 461.4 461.4 576 320 576L101.1 576C87.4 576 80.6 559.5 90.2 549.8L139 501C92.7 454.7 64 390.7 64 320zM413.6 217.6C437.2 217.6 456.3 198.5 456.3 174.9C456.3 151.3 437.2 132.2 413.6 132.2C393 132.2 375.8 146.8 371.8 166.2C337.3 169.9 310.4 199.2 310.4 234.6L310.4 234.8C272.9 236.4 238.6 247.1 211.4 263.9C201.3 256.1 188.6 251.4 174.9 251.4C141.9 251.4 115.1 278.2 115.1 311.2C115.1 335.2 129.2 355.8 149.5 365.3C151.5 434.7 227.1 490.5 320.1 490.5C413.1 490.5 488.8 434.6 490.7 365.2C510.9 355.6 524.8 335 524.8 311.2C524.8 278.2 498 251.4 465 251.4C451.3 251.4 438.7 256 428.6 263.8C401.2 246.8 366.5 236.1 328.6 234.7L328.6 234.5C328.6 209.1 347.5 188 372 184.6C376.4 203.4 393.3 217.4 413.5 217.4L413.6 217.6zM241.1 310.9C257.8 310.9 270.6 328.5 269.6 350.2C268.6 371.9 256.1 379.8 239.3 379.8C222.5 379.8 207.9 371 208.9 349.3C209.9 327.6 224.3 311 241 311L241.1 310.9zM431.2 349.2C432.2 370.9 417.5 379.7 400.8 379.7C384.1 379.7 371.5 371.8 370.5 350.1C369.5 328.4 382.3 310.8 399 310.8C415.7 310.8 430.2 327.4 431.1 349.1L431.2 349.2zM383.1 405.9C372.8 430.5 348.5 447.8 320.1 447.8C291.7 447.8 267.4 430.5 257.1 405.9C255.9 403 257.9 399.7 261 399.4C279.4 397.5 299.3 396.5 320.1 396.5C340.9 396.5 360.8 397.5 379.2 399.4C382.3 399.7 384.3 403 383.1 405.9z"
  ]);
}
function mastodonIcon() {
  return createSvg("0 0 640 640", [
    "M529 243.1C529 145.9 465.3 117.4 465.3 117.4C402.8 88.7 236.7 89 174.8 117.4C174.8 117.4 111.1 145.9 111.1 243.1C111.1 358.8 104.5 502.5 216.7 532.2C257.2 542.9 292 545.2 320 543.6C370.8 540.8 399.3 525.5 399.3 525.5L397.6 488.6C397.6 488.6 361.3 500 320.5 498.7C280.1 497.3 237.5 494.3 230.9 444.7C230.3 440.1 230 435.4 230 430.8C315.6 451.7 388.7 439.9 408.7 437.5C464.8 430.8 513.7 396.2 519.9 364.6C529.7 314.8 528.9 243.1 528.9 243.1zM453.9 368.3L407.3 368.3L407.3 254.1C407.3 204.4 343.3 202.5 343.3 261L343.3 323.5L297 323.5L297 261C297 202.5 233 204.4 233 254.1L233 368.3L186.3 368.3C186.3 246.2 181.1 220.4 204.7 193.3C230.6 164.4 284.5 162.5 308.5 199.4L320.1 218.9L331.7 199.4C355.8 162.3 409.8 164.6 435.5 193.3C459.2 220.6 453.9 246.3 453.9 368.3L453.9 368.3z"
  ]);
}

// src/providers/github-gist.ts
var GIST_PATTERN = /gist\.github\.com\/([a-zA-Z0-9_-]+)\/([a-f0-9]+)/;
function createGithubGistProvider(cache, token) {
  return {
    id: "github-gist",
    name: "GitHub Gist",
    test(url) {
      return GIST_PATTERN.test(url);
    },
    async render(url, container, theme) {
      const match = url.match(GIST_PATTERN);
      if (!match) return;
      const [, , gistId] = match;
      const cacheKey = `gist:${gistId}`;
      container.addClass("extended-embed", "extended-embed-gist");
      const loading = container.createDiv("extended-embed-loading");
      loading.setText("Loading gist...");
      let data = null;
      const cached = cache.get(cacheKey);
      if (cached) {
        data = cached;
      } else {
        try {
          const headers = {
            Accept: "application/vnd.github.v3+json"
          };
          if (token) {
            headers.Authorization = `Bearer ${token}`;
          }
          const response = await (0, import_obsidian4.requestUrl)({
            url: `https://api.github.com/gists/${gistId}`,
            headers
          });
          data = response.json;
          cache.set(cacheKey, data);
        } catch (e) {
          loading.setText("Failed to load gist");
          loading.addClass("extended-embed-error");
          return;
        }
      }
      loading.remove();
      const isDark = theme === "dark";
      const files = Object.values(data.files);
      const card = container.createDiv({
        cls: `extended-embed-card extended-embed-gist-card ${isDark ? "extended-embed-dark" : "extended-embed-light"}`
      });
      const header = card.createDiv("extended-embed-card-header");
      const gistIcon = header.createSpan("extended-embed-stat-icon");
      (0, import_obsidian4.setIcon)(gistIcon, "code");
      if (data.owner) {
        header.createEl("img", {
          cls: "extended-embed-avatar",
          attr: { src: data.owner.avatar_url, alt: data.owner.login, width: "20", height: "20" }
        });
        header.createEl("a", {
          cls: "extended-embed-gist-owner",
          text: data.owner.login,
          attr: { href: `https://github.com/${data.owner.login}`, target: "_blank", rel: "noopener noreferrer" }
        });
      }
      header.appendChild(githubIcon());
      const gistTitle = data.description || Object.keys(data.files)[0] || "View gist";
      card.createEl("a", {
        cls: "extended-embed-gist-title",
        text: gistTitle,
        attr: { href: data.html_url, target: "_blank", rel: "noopener noreferrer" }
      });
      const maxFiles = 2;
      const maxLines = 12;
      for (const file of files.slice(0, maxFiles)) {
        const fileBlock = card.createDiv("extended-embed-gist-file");
        const fileHeader = fileBlock.createDiv("extended-embed-gist-file-header");
        const fileIcon = fileHeader.createSpan("extended-embed-stat-icon");
        (0, import_obsidian4.setIcon)(fileIcon, "file-text");
        fileHeader.createSpan({ text: file.filename, cls: "extended-embed-gist-filename" });
        const lines = file.content.split("\n");
        const preview = lines.slice(0, maxLines).join("\n");
        const truncated = lines.length > maxLines || file.truncated;
        const pre = fileBlock.createEl("pre", { cls: "extended-embed-gist-code" });
        const code = pre.createEl("code");
        code.setText(preview + (truncated ? "\n..." : ""));
      }
      if (files.length > maxFiles) {
        card.createEl("p", {
          cls: "extended-embed-subtitle",
          text: `+${files.length - maxFiles} more file${files.length - maxFiles > 1 ? "s" : ""}`
        });
      }
    }
  };
}

// src/providers/github-repo.ts
var import_obsidian5 = require("obsidian");
var REPO_PATTERN = /^https?:\/\/github\.com\/([a-zA-Z0-9._-]+)\/([a-zA-Z0-9._-]+)\/?$/;
function formatCount(n) {
  if (n >= 1e3) {
    return `${(n / 1e3).toFixed(1).replace(/\.0$/, "")}k`;
  }
  return String(n);
}
var LANGUAGE_COLORS = {
  JavaScript: "#f1e05a",
  TypeScript: "#3178c6",
  Python: "#3572A5",
  Java: "#b07219",
  Go: "#00ADD8",
  Rust: "#dea584",
  Ruby: "#701516",
  PHP: "#4F5D95",
  "C#": "#178600",
  "C++": "#f34b7d",
  C: "#555555",
  Swift: "#F05138",
  Kotlin: "#A97BFF",
  Dart: "#00B4AB",
  Shell: "#89e051",
  HTML: "#e34c26",
  CSS: "#563d7c",
  Vue: "#41b883",
  Svelte: "#ff3e00",
  Astro: "#ff5a03",
  Lua: "#000080",
  Zig: "#ec915c"
};
function createGithubRepoProvider(cache, token) {
  return {
    id: "github-repo",
    name: "GitHub repository",
    test(url) {
      return REPO_PATTERN.test(url);
    },
    async render(url, container, theme) {
      var _a;
      const match = url.match(REPO_PATTERN);
      if (!match) return;
      const [, owner, repo] = match;
      const cacheKey = `github-repo:${owner}/${repo}`;
      container.addClass("extended-embed", "extended-embed-github-repo");
      const loading = container.createDiv("extended-embed-loading");
      loading.setText("Loading repository...");
      let data = null;
      const cached = cache.get(cacheKey);
      if (cached) {
        data = cached;
      } else {
        try {
          const headers = {
            Accept: "application/vnd.github.v3+json"
          };
          if (token) {
            headers.Authorization = `Bearer ${token}`;
          }
          const response = await (0, import_obsidian5.requestUrl)({
            url: `https://api.github.com/repos/${owner}/${repo}`,
            headers
          });
          data = response.json;
          cache.set(cacheKey, data);
        } catch (e) {
          loading.setText("Failed to load repository");
          loading.addClass("extended-embed-error");
          return;
        }
      }
      loading.remove();
      const isDark = theme === "dark";
      const card = container.createDiv({
        cls: `extended-embed-card ${isDark ? "extended-embed-dark" : "extended-embed-light"}`
      });
      const header = card.createDiv("extended-embed-card-header");
      header.createEl("img", {
        cls: "extended-embed-avatar",
        attr: { src: data.owner.avatar_url, alt: data.owner.login, width: "20", height: "20" }
      });
      header.createEl("a", {
        cls: "extended-embed-repo-name",
        text: data.full_name,
        attr: { href: data.html_url, target: "_blank", rel: "noopener noreferrer" }
      });
      header.appendChild(githubIcon());
      if (data.description) {
        card.createEl("p", { cls: "extended-embed-description", text: data.description });
      }
      const footer = card.createDiv("extended-embed-card-footer");
      if (data.language) {
        const langEl = footer.createSpan("extended-embed-language");
        const color = (_a = LANGUAGE_COLORS[data.language]) != null ? _a : "#8b949e";
        langEl.createSpan({
          cls: "extended-embed-lang-dot",
          attr: { style: `background-color: ${color}` }
        });
        langEl.createSpan({ text: data.language });
      }
      if (data.stargazers_count > 0) {
        const stars = footer.createSpan("extended-embed-stat");
        const starIcon = stars.createSpan("extended-embed-stat-icon");
        (0, import_obsidian5.setIcon)(starIcon, "star");
        stars.createSpan({ text: formatCount(data.stargazers_count) });
      }
      if (data.forks_count > 0) {
        const forks = footer.createSpan("extended-embed-stat");
        const forkIcon = forks.createSpan("extended-embed-stat-icon");
        (0, import_obsidian5.setIcon)(forkIcon, "git-fork");
        forks.createSpan({ text: formatCount(data.forks_count) });
      }
    }
  };
}

// src/providers/github-issue.ts
var import_obsidian6 = require("obsidian");
var ISSUE_PATTERN = /^https?:\/\/github\.com\/([a-zA-Z0-9._-]+)\/([a-zA-Z0-9._-]+)\/(issues|pull)\/(\d+)\/?$/;
function getStateInfo(data, isPR) {
  var _a;
  if (isPR && ((_a = data.pull_request) == null ? void 0 : _a.merged_at)) {
    return { label: "Merged", cls: "extended-embed-state-merged" };
  }
  if (data.state === "open") {
    return { label: "Open", cls: "extended-embed-state-open" };
  }
  return { label: "Closed", cls: "extended-embed-state-closed" };
}
function formatDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function createGithubIssueProvider(cache, token) {
  return {
    id: "github-issue",
    name: "GitHub issue/PR",
    test(url) {
      return ISSUE_PATTERN.test(url);
    },
    async render(url, container, theme) {
      const match = url.match(ISSUE_PATTERN);
      if (!match) return;
      const [, owner, repo, type, number] = match;
      const isPR = type === "pull";
      const apiPath = isPR ? "pulls" : "issues";
      const cacheKey = `github-issue:${owner}/${repo}/${number}`;
      container.addClass("extended-embed", "extended-embed-github-issue");
      const loading = container.createDiv("extended-embed-loading");
      loading.setText(`Loading ${isPR ? "pull request" : "issue"}...`);
      let data = null;
      const cached = cache.get(cacheKey);
      if (cached) {
        data = cached;
      } else {
        try {
          const headers = {
            Accept: "application/vnd.github.v3+json"
          };
          if (token) {
            headers.Authorization = `Bearer ${token}`;
          }
          const response = await (0, import_obsidian6.requestUrl)({
            url: `https://api.github.com/repos/${owner}/${repo}/${apiPath}/${number}`,
            headers
          });
          data = response.json;
          cache.set(cacheKey, data);
        } catch (e) {
          loading.setText(`Failed to load ${isPR ? "pull request" : "issue"}`);
          loading.addClass("extended-embed-error");
          return;
        }
      }
      loading.remove();
      const isDark = theme === "dark";
      const stateInfo = getStateInfo(data, isPR);
      const card = container.createDiv({
        cls: `extended-embed-card ${isDark ? "extended-embed-dark" : "extended-embed-light"}`
      });
      const header = card.createDiv("extended-embed-card-header");
      header.createSpan({
        cls: `extended-embed-state-badge ${stateInfo.cls}`,
        text: stateInfo.label
      });
      header.createEl("a", {
        cls: "extended-embed-issue-title",
        text: data.title,
        attr: { href: data.html_url, target: "_blank", rel: "noopener noreferrer" }
      });
      header.appendChild(githubIcon());
      card.createEl("p", {
        cls: "extended-embed-subtitle",
        text: `${owner}/${repo} #${data.number}`
      });
      const footer = card.createDiv("extended-embed-card-footer");
      if (data.labels.length > 0) {
        const labelsEl = footer.createSpan("extended-embed-labels");
        for (const label of data.labels.slice(0, 3)) {
          labelsEl.createSpan({
            cls: "extended-embed-label",
            text: label.name,
            attr: {
              style: `background-color: #${label.color}; color: ${isLightColor(label.color) ? "#000" : "#fff"}`
            }
          });
        }
      }
      const meta = footer.createSpan("extended-embed-meta");
      meta.createEl("img", {
        cls: "extended-embed-avatar-small",
        attr: { src: data.user.avatar_url, alt: data.user.login, width: "16", height: "16" }
      });
      meta.createSpan({ text: `${data.user.login} on ${formatDate(data.created_at)}` });
    }
  };
}
function isLightColor(hex) {
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.5;
}

// src/providers/reddit.ts
var import_obsidian7 = require("obsidian");
var REDDIT_PATTERN = /^https?:\/\/(?:www\.|old\.|np\.)?reddit\.com\/r\/([a-zA-Z0-9_]+)\/comments\/([a-zA-Z0-9]+)/;
function formatCount2(n) {
  if (n >= 1e3) return `${(n / 1e3).toFixed(1)}k`;
  return String(n);
}
function formatDate2(utc) {
  const d = new Date(utc * 1e3);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function createRedditProvider(cache) {
  return {
    id: "reddit",
    name: "Reddit",
    test(url) {
      return REDDIT_PATTERN.test(url);
    },
    async render(url, container, theme) {
      var _a, _b, _c, _d, _e;
      const match = url.match(REDDIT_PATTERN);
      if (!match) return;
      const subreddit = (_a = match[1]) != null ? _a : "";
      const postId = (_b = match[2]) != null ? _b : "";
      const cacheKey = `reddit:${subreddit}/${postId}`;
      container.addClass("extended-embed", "extended-embed-reddit");
      const loading = container.createDiv("extended-embed-loading");
      loading.setText("Loading post...");
      let post = null;
      const cached = cache.get(cacheKey);
      if (cached) {
        post = cached;
      } else {
        try {
          const response = await (0, import_obsidian7.requestUrl)({
            url: `https://www.reddit.com/r/${subreddit}/comments/${postId}.json`,
            headers: { Accept: "application/json" }
          });
          const listing = response.json;
          const firstChild = (_e = (_d = (_c = listing[0]) == null ? void 0 : _c.data) == null ? void 0 : _d.children[0]) == null ? void 0 : _e.data;
          if (firstChild) {
            post = firstChild;
            cache.set(cacheKey, post);
          }
        } catch (e) {
          loading.setText("Failed to load post");
          loading.addClass("extended-embed-error");
          return;
        }
      }
      if (!post) {
        loading.setText("Failed to load post");
        loading.addClass("extended-embed-error");
        return;
      }
      loading.remove();
      const isDark = theme === "dark";
      const postUrl = `https://www.reddit.com${post.permalink}`;
      const card = container.createDiv({
        cls: `extended-embed-card ${isDark ? "extended-embed-dark" : "extended-embed-light"}`
      });
      const header = card.createDiv("extended-embed-card-header");
      header.createEl("a", {
        cls: "extended-embed-reddit-subreddit",
        text: post.subreddit_name_prefixed,
        attr: { href: `https://www.reddit.com/${post.subreddit_name_prefixed}/`, target: "_blank", rel: "noopener noreferrer" }
      });
      const meta = header.createSpan({ cls: "extended-embed-reddit-meta" });
      meta.appendText("Posted by ");
      meta.createEl("a", {
        cls: "extended-embed-reddit-author-link",
        text: `u/${post.author}`,
        attr: { href: `https://www.reddit.com/user/${post.author}/`, target: "_blank", rel: "noopener noreferrer" }
      });
      meta.appendText(` on ${formatDate2(post.created_utc)}`);
      header.appendChild(redditIcon());
      if (post.link_flair_text) {
        header.createSpan({
          cls: "extended-embed-reddit-flair",
          text: post.link_flair_text
        });
      }
      card.createEl("a", {
        cls: "extended-embed-reddit-title",
        text: post.title,
        attr: { href: postUrl, target: "_blank", rel: "noopener noreferrer" }
      });
      if (post.is_self && post.selftext) {
        const truncated = post.selftext.length > 300 ? post.selftext.substring(0, 300) + "..." : post.selftext;
        card.createEl("p", {
          cls: "extended-embed-reddit-body",
          text: truncated
        });
      }
      const footer = card.createDiv("extended-embed-card-footer");
      footer.createSpan({
        cls: "extended-embed-stat",
        text: `${formatCount2(post.score)} upvotes`
      });
      footer.createSpan({
        cls: "extended-embed-stat",
        text: `${formatCount2(post.num_comments)} comments`
      });
    }
  };
}

// src/providers/bluesky.ts
var import_obsidian8 = require("obsidian");
var BLUESKY_PATTERN = /^https?:\/\/bsky\.app\/profile\/([a-zA-Z0-9._:-]+)\/post\/([a-zA-Z0-9]+)\/?$/;
function formatDate3(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function formatCount3(n) {
  if (n >= 1e3) return `${(n / 1e3).toFixed(1)}k`;
  return String(n);
}
function createBlueskyProvider(cache) {
  return {
    id: "bluesky",
    name: "Bluesky",
    test(url) {
      return BLUESKY_PATTERN.test(url);
    },
    async render(url, container, theme) {
      var _a, _b, _c;
      const match = url.match(BLUESKY_PATTERN);
      if (!match) return;
      const handle = (_a = match[1]) != null ? _a : "";
      const postId = (_b = match[2]) != null ? _b : "";
      const cacheKey = `bluesky:${handle}/${postId}`;
      container.addClass("extended-embed", "extended-embed-bluesky");
      const loading = container.createDiv("extended-embed-loading");
      loading.setText("Loading post...");
      let post = null;
      const cached = cache.get(cacheKey);
      if (cached) {
        post = cached;
      } else {
        try {
          const profileRes = await (0, import_obsidian8.requestUrl)({
            url: `https://public.api.bsky.app/xrpc/com.atproto.identity.resolveHandle?handle=${encodeURIComponent(handle)}`
          });
          const did = profileRes.json.did;
          const atUri = `at://${did}/app.bsky.feed.post/${postId}`;
          const postRes = await (0, import_obsidian8.requestUrl)({
            url: `https://public.api.bsky.app/xrpc/app.bsky.feed.getPosts?uris=${encodeURIComponent(atUri)}`
          });
          const posts = postRes.json.posts;
          if (posts.length > 0) {
            const p = posts[0];
            if (p) {
              post = p;
              cache.set(cacheKey, post);
            }
          }
        } catch (e) {
          loading.setText("Failed to load post");
          loading.addClass("extended-embed-error");
          return;
        }
      }
      if (!post) {
        loading.setText("Failed to load post");
        loading.addClass("extended-embed-error");
        return;
      }
      loading.remove();
      const isDark = theme === "dark";
      const card = container.createDiv({
        cls: `extended-embed-card ${isDark ? "extended-embed-dark" : "extended-embed-light"}`
      });
      const header = card.createDiv("extended-embed-card-header");
      if (post.author.avatar) {
        header.createEl("img", {
          cls: "extended-embed-avatar-small",
          attr: { src: post.author.avatar, alt: post.author.handle, width: "20", height: "20" }
        });
      }
      const nameWrap = header.createSpan("extended-embed-bluesky-author");
      if (post.author.displayName) {
        nameWrap.createSpan({ cls: "extended-embed-bluesky-displayname", text: post.author.displayName });
      }
      nameWrap.createEl("a", {
        cls: "extended-embed-bluesky-handle",
        text: `@${post.author.handle}`,
        attr: { href: `https://bsky.app/profile/${post.author.handle}`, target: "_blank", rel: "noopener noreferrer" }
      });
      header.appendChild(blueskyIcon());
      card.createEl("p", {
        cls: "extended-embed-bluesky-text",
        text: post.record.text
      });
      const images = (_c = post.embed) == null ? void 0 : _c.images;
      if (images && images.length > 0) {
        const firstImage = images[0];
        if (firstImage) {
          card.createEl("img", {
            cls: "extended-embed-bluesky-media",
            attr: {
              src: firstImage.thumb,
              alt: firstImage.alt || "",
              loading: "lazy"
            }
          });
        }
      }
      const footer = card.createDiv("extended-embed-card-footer");
      footer.createEl("a", {
        text: formatDate3(post.record.createdAt),
        attr: { href: url, target: "_blank", rel: "noopener noreferrer" }
      });
      if (post.replyCount != null && post.replyCount > 0) {
        footer.createSpan({ cls: "extended-embed-stat", text: `${formatCount3(post.replyCount)} replies` });
      }
      if (post.repostCount != null && post.repostCount > 0) {
        footer.createSpan({ cls: "extended-embed-stat", text: `${formatCount3(post.repostCount)} reposts` });
      }
      if (post.likeCount != null && post.likeCount > 0) {
        footer.createSpan({ cls: "extended-embed-stat", text: `${formatCount3(post.likeCount)} likes` });
      }
    }
  };
}

// src/providers/mastodon.ts
var import_obsidian9 = require("obsidian");
var MASTODON_PATTERN = /^https?:\/\/([a-zA-Z0-9.-]+)\/@([a-zA-Z0-9_]+)\/(\d+)\/?$/;
function formatDate4(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function formatCount4(n) {
  if (n >= 1e3) return `${(n / 1e3).toFixed(1)}k`;
  return String(n);
}
function blockToText(el) {
  var _a;
  el.querySelectorAll("br").forEach((br) => br.replaceWith("\n"));
  return (_a = el.textContent) != null ? _a : "";
}
function htmlToPlainText(html) {
  const doc = new DOMParser().parseFromString(html, "text/html");
  const paragraphs = [];
  const ps = doc.querySelectorAll("p");
  if (ps.length > 0) {
    ps.forEach((p) => paragraphs.push(blockToText(p)));
  } else {
    paragraphs.push(blockToText(doc.body));
  }
  return paragraphs.join("\n\n").trim();
}
function createMastodonProvider(cache) {
  return {
    id: "mastodon",
    name: "Mastodon",
    test(url) {
      return MASTODON_PATTERN.test(url);
    },
    async render(url, container, theme) {
      var _a, _b, _c;
      const match = url.match(MASTODON_PATTERN);
      if (!match) return;
      const instance = (_a = match[1]) != null ? _a : "";
      const postId = (_b = match[3]) != null ? _b : "";
      const cacheKey = `mastodon:${instance}/${postId}`;
      container.addClass("extended-embed", "extended-embed-mastodon");
      const loading = container.createDiv("extended-embed-loading");
      loading.setText("Loading post...");
      let status = null;
      const cached = cache.get(cacheKey);
      if (cached) {
        status = cached;
      } else {
        try {
          const response = await (0, import_obsidian9.requestUrl)({
            url: `https://${instance}/api/v1/statuses/${postId}`,
            headers: { Accept: "application/json" }
          });
          status = response.json;
          cache.set(cacheKey, status);
        } catch (e) {
          loading.setText("Failed to load post");
          loading.addClass("extended-embed-error");
          return;
        }
      }
      if (!status) {
        loading.setText("Failed to load post");
        loading.addClass("extended-embed-error");
        return;
      }
      loading.remove();
      const isDark = theme === "dark";
      const card = container.createDiv({
        cls: `extended-embed-card ${isDark ? "extended-embed-dark" : "extended-embed-light"}`
      });
      const header = card.createDiv("extended-embed-card-header");
      header.createEl("img", {
        cls: "extended-embed-avatar-small",
        attr: { src: status.account.avatar, alt: status.account.acct, width: "20", height: "20" }
      });
      const nameWrap = header.createSpan("extended-embed-mastodon-author");
      if (status.account.display_name) {
        nameWrap.createSpan({ cls: "extended-embed-mastodon-displayname", text: status.account.display_name });
      }
      nameWrap.createEl("a", {
        cls: "extended-embed-mastodon-handle",
        text: `@${status.account.acct}@${instance}`,
        attr: { href: status.account.url, target: "_blank", rel: "noopener noreferrer" }
      });
      header.appendChild(mastodonIcon());
      const plainText = htmlToPlainText(status.content);
      card.createEl("p", {
        cls: "extended-embed-mastodon-text",
        text: plainText
      });
      if (status.media_attachments && status.media_attachments.length > 0) {
        const firstMedia = status.media_attachments[0];
        if (firstMedia && firstMedia.type === "image" && firstMedia.preview_url) {
          card.createEl("img", {
            cls: "extended-embed-mastodon-media",
            attr: {
              src: firstMedia.preview_url,
              alt: (_c = firstMedia.description) != null ? _c : "",
              loading: "lazy"
            }
          });
        }
      }
      const footer = card.createDiv("extended-embed-card-footer");
      footer.createEl("a", {
        text: formatDate4(status.created_at),
        attr: { href: status.url, target: "_blank", rel: "noopener noreferrer" }
      });
      if (status.replies_count > 0) {
        footer.createSpan({ cls: "extended-embed-stat", text: `${formatCount4(status.replies_count)} replies` });
      }
      if (status.reblogs_count > 0) {
        footer.createSpan({ cls: "extended-embed-stat", text: `${formatCount4(status.reblogs_count)} boosts` });
      }
      if (status.favourites_count > 0) {
        footer.createSpan({ cls: "extended-embed-stat", text: `${formatCount4(status.favourites_count)} favorites` });
      }
    }
  };
}

// src/providers/linkedin.ts
var LINKEDIN_PATTERN = /linkedin\.com\/(?:embed\/)?(?:posts\/.*?(activity)-|feed\/update\/urn:li:(share|activity|ugcPost):)([0-9]+)/;
var linkedinProvider = {
  id: "linkedin",
  name: "LinkedIn",
  test(url) {
    return LINKEDIN_PATTERN.test(url);
  },
  render(url, container, theme) {
    const match = url.match(LINKEDIN_PATTERN);
    if (!match) return;
    const [, activityType, urnType, id] = match;
    const type = activityType || urnType;
    let embedUrl;
    let search = "";
    try {
      const urlObj = new URL(url);
      search = urlObj.search;
      if (urlObj.pathname.includes("/embed/feed/update/")) {
        embedUrl = `${urlObj.origin}${urlObj.pathname}${urlObj.search}`;
      } else {
        embedUrl = `https://www.linkedin.com/embed/feed/update/urn:li:${type}:${id}${search}`;
      }
    } catch (e) {
      embedUrl = `https://www.linkedin.com/embed/feed/update/urn:li:${type}:${id}`;
    }
    const liMode = search.includes("compact=1") ? "compact" : search.includes("collapsed=1") ? "collapsed" : "full";
    container.addClass("extended-embed", "extended-embed-linkedin");
    container.setAttribute("data-li-mode", liMode);
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        style: "border:none",
        frameborder: "0",
        allowfullscreen: "",
        title: "Embedded post",
        loading: "lazy"
      }
    });
  }
};

// src/providers/steam.ts
var STEAM_APP_PATTERN = /store\.steampowered\.com\/app\/(\d+)/;
var STEAM_BUNDLE_PATTERN = /store\.steampowered\.com\/bundle\/(\d+)/;
var STEAM_SUB_PATTERN = /store\.steampowered\.com\/sub\/(\d+)/;
function getSteamEmbedUrl(url) {
  let match = url.match(STEAM_APP_PATTERN);
  if (match) return `https://store.steampowered.com/widget/${match[1]}/`;
  match = url.match(STEAM_BUNDLE_PATTERN);
  if (match) return `https://store.steampowered.com/widget/bundle/${match[1]}/`;
  match = url.match(STEAM_SUB_PATTERN);
  if (match) return `https://store.steampowered.com/widget/${match[1]}/`;
  return null;
}
var steamProvider = {
  id: "steam",
  name: "Steam",
  test(url) {
    return STEAM_APP_PATTERN.test(url) || STEAM_BUNDLE_PATTERN.test(url) || STEAM_SUB_PATTERN.test(url);
  },
  render(url, container, _theme) {
    const embedUrl = getSteamEmbedUrl(url);
    if (!embedUrl) return;
    container.addClass("extended-embed", "extended-embed-steam");
    container.createEl("iframe", {
      attr: {
        src: embedUrl,
        frameborder: "0",
        loading: "lazy",
        style: "height: 190px"
      }
    });
  }
};

// src/providers/opengraph.ts
var import_obsidian10 = require("obsidian");
async function fetchOGData(url) {
  var _a;
  const response = await (0, import_obsidian10.requestUrl)({
    url,
    headers: { Accept: "text/html" }
  });
  const html = response.text;
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, "text/html");
  function getMeta(property) {
    var _a2;
    const el = doc.querySelector(`meta[property="${property}"], meta[name="${property}"]`);
    return (_a2 = el == null ? void 0 : el.getAttribute("content")) != null ? _a2 : "";
  }
  const parsedUrl = new URL(url);
  return {
    title: getMeta("og:title") || ((_a = doc.querySelector("title")) == null ? void 0 : _a.textContent) || parsedUrl.hostname,
    description: getMeta("og:description") || getMeta("description"),
    image: getMeta("og:image"),
    favicon: `https://www.google.com/s2/favicons?domain=${parsedUrl.hostname}&sz=32`,
    siteName: getMeta("og:site_name") || parsedUrl.hostname,
    url
  };
}
function createOpenGraphProvider(cache) {
  return {
    id: "opengraph",
    name: "Generic URL preview",
    test(url) {
      try {
        const parsed = new URL(url);
        return parsed.protocol === "http:" || parsed.protocol === "https:";
      } catch (e) {
        return false;
      }
    },
    async render(url, container, theme) {
      const cacheKey = `og:${url}`;
      container.addClass("extended-embed", "extended-embed-opengraph");
      const loading = container.createDiv("extended-embed-loading");
      loading.setText("Loading preview...");
      let data = null;
      const cached = cache.get(cacheKey);
      if (cached) {
        data = cached;
      } else {
        try {
          data = await fetchOGData(url);
          cache.set(cacheKey, data);
        } catch (e) {
          loading.setText("Failed to load preview");
          loading.addClass("extended-embed-error");
          return;
        }
      }
      loading.remove();
      const isDark = theme === "dark";
      const card = container.createDiv({
        cls: `extended-embed-card extended-embed-og-card ${isDark ? "extended-embed-dark" : "extended-embed-light"}`
      });
      if (data.image) {
        const imageLink = card.createEl("a", {
          cls: "extended-embed-og-image-link",
          attr: { href: data.url, target: "_blank" }
        });
        imageLink.createEl("img", {
          cls: "extended-embed-og-image",
          attr: { src: data.image, alt: data.title, loading: "lazy" }
        });
      }
      const body = card.createDiv("extended-embed-og-body");
      const siteRow = body.createDiv("extended-embed-og-site");
      siteRow.createEl("img", {
        cls: "extended-embed-favicon",
        attr: { src: data.favicon, alt: "", width: "16", height: "16" }
      });
      siteRow.createSpan({ text: data.siteName });
      body.createEl("a", {
        cls: "extended-embed-og-title",
        text: data.title,
        attr: { href: data.url, target: "_blank" }
      });
      if (data.description) {
        const desc = data.description.length > 160 ? data.description.substring(0, 160) + "..." : data.description;
        body.createEl("p", { cls: "extended-embed-og-desc", text: desc });
      }
    }
  };
}

// src/embed-manager.ts
var EmbedManager = class {
  constructor(settings, cache, app) {
    this.settings = settings;
    this.cache = cache;
    this.app = app;
    this.providers = [];
    this.rebuildProviders();
  }
  getGithubToken() {
    var _a;
    if ((0, import_obsidian11.requireApiVersion)("1.11.4") && this.settings.githubTokenSecretId) {
      const secretStorage = this.app.secretStorage;
      if (secretStorage) {
        return (_a = secretStorage.getSecret(this.settings.githubTokenSecretId)) != null ? _a : "";
      }
    }
    return this.settings.githubToken;
  }
  rebuildProviders() {
    const s = this.settings;
    const token = this.getGithubToken();
    this.providers = [];
    if (s.enableVimeo) this.providers.push(vimeoProvider);
    if (s.enableSpotify) this.providers.push(spotifyProvider);
    if (s.enableAppleMusic) this.providers.push(appleMusicProvider);
    if (s.enableSoundcloud) this.providers.push(soundcloudProvider);
    if (s.enableBandcamp) this.providers.push(bandcampProvider);
    if (s.enableCodepen) this.providers.push(codepenProvider);
    if (s.enableFigma) this.providers.push(figmaProvider);
    if (s.enableGithubGist) this.providers.push(createGithubGistProvider(this.cache, token));
    if (s.enableGithubIssue) this.providers.push(createGithubIssueProvider(this.cache, token));
    if (s.enableGithubRepo) this.providers.push(createGithubRepoProvider(this.cache, token));
    if (s.enableReddit) this.providers.push(createRedditProvider(this.cache));
    if (s.enableBluesky) this.providers.push(createBlueskyProvider(this.cache));
    if (s.enableMastodon) this.providers.push(createMastodonProvider(this.cache));
    if (s.enableLinkedin) this.providers.push(linkedinProvider);
    if (s.enableSteam) this.providers.push(steamProvider);
    if (s.enableOpengraph) this.providers.push(createOpenGraphProvider(this.cache));
  }
  getTheme() {
    if (this.settings.themeMode === "auto") {
      return document.body.classList.contains("theme-dark") ? "dark" : "light";
    }
    return this.settings.themeMode;
  }
  findProvider(url) {
    for (const provider of this.providers) {
      if (provider.test(url)) return provider;
    }
    return null;
  }
  async render(url, container) {
    const provider = this.findProvider(url);
    if (!provider) return false;
    const theme = this.getTheme();
    await provider.render(url, container, theme);
    return true;
  }
};

// src/main.ts
function parseSource(source) {
  var _a, _b;
  const lines = source.trim().split("\n").map((l) => l.trim()).filter(Boolean);
  if (lines.length === 0) return null;
  const url = (_a = lines[0]) != null ? _a : "";
  if (!url.startsWith("http://") && !url.startsWith("https://")) return null;
  let width;
  let height;
  if (lines.length > 1) {
    const dimMatch = ((_b = lines[1]) != null ? _b : "").match(/^(\d+)(?:x(\d+))?$/);
    if (dimMatch) {
      const w = dimMatch[1];
      const h = dimMatch[2];
      if (w) width = parseInt(w, 10);
      if (h) height = parseInt(h, 10);
    }
  }
  return { url, width, height };
}
var ExtendedEmbedsPlugin = class extends import_obsidian12.Plugin {
  async onload() {
    await this.loadSettings();
    await this.migrateTokenToSecret();
    this.cache = createCacheManager(this.settings.cacheTtlMinutes);
    this.embedManager = new EmbedManager(this.settings, this.cache, this.app);
    this.addSettingTab(new ExtendedEmbedsSettingTab(this.app, this));
    this.registerInsertCommand();
    this.registerMarkdownCodeBlockProcessor("embed", (source, el, ctx) => {
      const parsed = parseSource(source);
      if (!parsed) {
        el.createDiv({ cls: "extended-embed-error", text: "Invalid embed: paste a URL" });
        return;
      }
      const wrapper = el.createDiv("extended-embed-wrapper");
      if (parsed.width) {
        wrapper.addClass("extended-embed-custom-width");
        wrapper.setCssProps({ "--embed-width": `${parsed.width}px` });
      }
      if (parsed.height) {
        wrapper.setCssProps({ "--embed-height": `${parsed.height}px` });
      }
      ctx.addChild(new EmbedRenderChild(wrapper, this.embedManager, parsed.url));
    });
  }
  registerInsertCommand() {
    this.addCommand({
      id: "insert-web-embed",
      name: "Add web embed",
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        const template = "```embed\n\n```";
        editor.replaceRange(template, cursor);
        editor.setCursor({ line: cursor.line + 1, ch: 0 });
      }
    });
  }
  /**
   * One-time migration of plaintext GitHub token to SecretStorage (1.11.4+).
   */
  async migrateTokenToSecret() {
    if (!(0, import_obsidian12.requireApiVersion)("1.11.4")) return;
    if (this.settings.githubTokenSecretId || !this.settings.githubToken) return;
    const secretStorage = this.app.secretStorage;
    if (!secretStorage) return;
    const secretId = "extended-embeds-github-token";
    try {
      secretStorage.setSecret(secretId, this.settings.githubToken);
      this.settings.githubTokenSecretId = secretId;
      await this.saveSettings();
    } catch (e) {
      new import_obsidian12.Notice("Failed to migrate token to secure storage, please re-enter it in settings.");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.embedManager) {
      this.cache = createCacheManager(this.settings.cacheTtlMinutes);
      this.embedManager = new EmbedManager(this.settings, this.cache, this.app);
    }
  }
};
var EmbedRenderChild = class extends import_obsidian12.MarkdownRenderChild {
  constructor(containerEl, embedManager, url) {
    super(containerEl);
    this.embedManager = embedManager;
    this.url = url;
  }
  onload() {
    void this.embedManager.render(this.url, this.containerEl);
  }
};

/* nosourcemap */